# Generated by Django 6.0.1 on 2026-01-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carowner',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
    ]
