from .teacher import Teacher
from .student import Student
from .subject import Subject
from .classroom import Classroom
from .schedule import Schedule
from .grade import Grade
from .school_class import SchoolClass
from .weekday import WeekDay
from .timeslot import TimeSlot
