# Generated by Django 6.0.1 on 2026-01-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_rename_date_of_birth_carowner_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
