from .teacher import TeacherViewSet
from .student import StudentViewSet
from .subject import SubjectViewSet
from .classroom import ClassroomViewSet
from .schedule import ScheduleViewSet
from .grade import GradeViewSet
from .school_class import SchoolClassViewSet
from .weekday import WeekDayViewSet
from .timeslot import TimeSlotViewSet
