# Generated by Django 6.0.1 on 2026-02-03 00:29

import datetime
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schedule_unique_together_alter_grade_value_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_classroom_per_slot',
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_teacher_per_slot',
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_class_per_slot',
        ),
        migrations.AddField(
            model_name='schedule',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeslot_schedule', to='core.timeslot'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('base', 'Базовый(ая)'), ('profile', 'Профильный(ая)')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('classroom', 'weekday', 'timeslot'), name='unique_classroom_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('teacher', 'weekday', 'timeslot'), name='unique_teacher_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('classroom', 'weekday', 'timeslot'), name='unique_class_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start_time'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', django.db.models.expressions.CombinedExpression(models.F('start_time'), '+', models.Value(datetime.timedelta(seconds=2700))))), name='min_duration_45_minutes'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_slot',
        ),
    ]
