from .teacher import TeacherSerializer
from .student import StudentSerializer
from .subject import SubjectSerializer
from .classroom import ClassroomSerializer
from .schedule import ScheduleSerializer
from .grade import GradeSerializer
from .school_class import SchoolClassSerializer
from .weekday import WeekDaySerializer
from .timeslot import TimeSlotSerializer
